#!/bin/bash
sudo apt-get install -y cython3 python3-pyqtgraph python3-numpy python3-matplotlib python3-scipy python3-hdf5storage python3-tqdm python3-psutil python3-setuptools python3-multipletau  python3-pip python3-pyqt5
sudo pip3 install pyusb